export default [
  {
    //question: "Êtes-vous un homme ou une femme?",
    //question: " Пожалуйста выберите ваш пол",
    question: "Please select your gender",
    questionimg: require("../../assets/questions/gender.png"),
    answer2: require("../../assets/questions/male.png"),
    answer3: require("../../assets/questions/female.png"),
    key: "1",
    finishtxt: "",
  },
  {
    question: "Are you pregnant?",
    questionimg: require("../../assets/questions/pregnant1.png"),
    answer2: require("../../assets/questions/yes1.png"),
    answer3: require("../../assets/questions/no.png"),
    key: "2",
    finishtxt: "",
  },
  {
    question: "What happened to you?",
    //question: "Что с вами случилось?",
    // question: "Que s'est-il passé?",
    questionimg: require("../../assets/questions/trauma.png"),
    answer2: require("../../assets/questions/crush.png"),
    answer3: require("../../assets/questions/attack.png"),
    answer6: require("../../assets/questions/caraccident.png"),
    answer7: require("../../assets/questions/fall.png"),
    key: "3",
    finishtxt: "",
  },
  {
    //question: "Où ressentez-vous la douleur?",
    question: "Where do you feel the pain?",
    //question: "Где вы чувствуете боль?",
    questionimg: require("../../assets/questions/pain.png"),
   // questionimg: require("../../assets/images/body.gif"),
   answer1: require("../../assets/questions/abdominal.png"),
    answer2: require("../../assets/questions/head.png"),
    answer3: require("../../assets/questions/chest.png"),
    answer4: require("../../assets/questions/dental.png"),
    answer6: require("../../assets/questions/eyep.png"),
    answer7: require("../../assets/questions/backp.png"),
    key: "4",
    finishtxt: "",
  },
  {
    question: "Do you have these symptoms?",
    questionimg: require("../../assets/questions/symptoms.png"),
    answer2: require("../../assets/questions/vomit.png"),
    answer3: require("../../assets/questions/weakness.png"),
    answer6: require("../../assets/questions/urinaryp.png"),
    answer7: require("../../assets/questions/confusion.png"),
    key: "5",
    finishtxt: "",
  },
  {
    question: "Do you have allergies?",
    questionimg: require("../../assets/questions/allergies.png"),
    answer2: require("../../assets/questions/yes1.png"),
    answer3: require("../../assets/questions/no.png"),
    key: "6",
    finishtxt: "",
  },
  {
    question: "Do you use drugs?",
    questionimg: require("../../assets/questions/cocaine.png"),
    answer2: require("../../assets/questions/yes1.png"),
    answer3: require("../../assets/questions/no.png"),
    key: "7",
    finishtxt: "",
  },
  {
    question: "Do you have cancer?",
    questionimg: require("../../assets/questions/cancer.png"),
    answer2: require("../../assets/questions/yes1.png"),
    answer3: require("../../assets/questions/no.png"),
    key: "8",
    finishtxt: "",
  },
  {
    question: "Please select your past diseases",
    questionimg: require("../../assets/questions/pastdisease.png"),
    answer2: require("../../assets/questions/diabet.png"),
    answer3: require("../../assets/questions/seizu.png"),
    answer6: require("../../assets/questions/breathep.png"),
    answer7: require("../../assets/questions/none2.jpg"),
    key: "9",
    finishtxt: "",
  },
  {
    question: "Do you have any heart problems?",
    questionimg: require("../../assets/questions/heartproblem.png"),
    answer1: require("../../assets/questions/angina.png"),
    answer2: require("../../assets/questions/arterialdisease.png"),
    answer3: require("../../assets/questions/heartfailure.png"),
    answer4: require("../../assets/questions/myocardial.png"),
    answer6: require("../../assets/questions/Stroke.png"),
    answer7: require("../../assets/questions/kidney.png"),
    answer8: require("../../assets/questions/none2.jpg"),
    key: "10",
    finishtxt: "",
  },
  {
    question: "Which medicine do you take? ",
    questionimg: require("../../assets/questions/takendrug.png"),
    answer1: require("../../assets/questions/carvedilol.png"),
    answer2: require("../../assets/questions/clexane.png"),
    answer3: require("../../assets/questions/atenolol.png"),
    answer4: require("../../assets/questions/trinitrina.png"),
    answer5: require("../../assets/questions/sectral.png"),
    answer6: require("../../assets/questions/fragmin.png"),
    answer7: require("../../assets/questions/aspirinetta.png"),
    answer8: require("../../assets/questions/none2.jpg"),
    finishtxt: "Finish the form",
    key: "11",
  },
];
